### ISSUE TITLE
I get eval results in weird places in the buffer

### ISSUE THREAD

**Issue by anonimitoraf** [flow-storm/cider-storm#3]
Hi @jpmonettas, this is awesome! I've just noticed that I get "extra" traces and the eval results show up in weird places (see traces 5 - 7)

https://github.com/jpmonettas/cider-storm/assets/15933322/c5f4c3a6-5e42-4e68-aa05-9bad63de6c66

Is this expected? Happy to give more info about my setup (if you need me to)

**Comment by anonimitoraf** [comment]
I've noticed that sometimes the "Cider - Debugging" text shows up beside the namespace

<img width="604" alt="image" src="https://github.com/jpmonettas/cider-storm/assets/15933322/f243fec7-5bb4-482f-a432-9cc838901067">

**Comment by jpmonettas** [comment]
Hi! Thanks @anonimitoraf for reporting this. The video was very helpful. https://github.com/jpmonettas/cider-storm/commit/c8a78a179fb572b732643ccfe332970d03d7fcff should fix that behavior. Please re-open if you see any other weird behavior like that.

**Comment by anonimitoraf** [comment]
Wow, so quick, thanks! Will try it out tomorrow

**Comment by anonimitoraf** [comment]
Thanks, works great!
