### ISSUE TITLE
Feature request - View Locals

### ISSUE THREAD

**Issue by danielneal** [flow-storm/cider-storm#4]
Just trying out ClojureStorm and cider-storm for the first time. 
It seems mind blowing. 

One thing I really miss from the cider debugger is view-locals. 
It's deep in my muscle memory. 

Could this be included in cider-storm?

**Comment by jpmonettas** [comment]
Hey sure! Just went and implemented a first version of it https://github.com/jpmonettas/cider-storm/commit/8cf23db37bde2085e2a5ca23e4f488e14b48a88c, so if you pull the latest commit you should have it under `l` (L)

A difference with the cider one (an important one) is that you can't dig those values using the cider-inspector.
I just created https://github.com/jpmonettas/cider-storm/issues/5 to track that.

In the meantime, remember that by just evaluating the `:dbg` keyword at the repl you can bring the whole FlowStorm UI over the same recordings, where you have inspectable locals and much more.

**Comment by danielneal** [comment]
Wow that was quick! 

I agree being able to dig in with the cider-inspector would be a great addition to this. 
Also there's a little bug where variables with an underscore (`a_b`) are displayed with a dash (`a-b`). 

But this is a great addition, thanks so much!

**Comment by danielneal** [comment]
Incidentally I think the command `D` also saves the bindings with `-` replacing `_` should I open another ticket for this?

**Comment by jpmonettas** [comment]
Sure, please open tickets for anything you think looks like a bug so we can track it!
